---
title: "Prepare raw population data"
output: html_document
---

# First step to load packages and file locations etc.
```{r include=FALSE}
rm(list=ls())

# 1a Declare root directory, folder locations and load essential stuff
project.folder <- paste0(print(here::here()),'/')
source(paste0(project.folder,'0_00_create_folder_structure.R'))
source(paste0(functions.folder,'script_initiate.R'))
```

# Load each year of raw population data and tidy up



## Add population data
```{r user-input1, include=TRUE}
# add inferred population data by day
pop.county <- readRDS(paste0(population_data,'countyPopulations_infer_by_days_new_years'))
head(pop.county,10)
```

## For each year, load and summarize
```{r user-input2, include=TRUE}
for(year_current in years_mortality){
  
  mortality.year.folder = paste0(mortality.folder,as.character(year_current),'/')
  ifelse(!dir.exists(mortality.year.folder), dir.create(mortality.year.folder), FALSE)
  
  # county population for that particular year
  pop.county.year = subset(pop.county,year==as.numeric(year_current))
  
  # process chosen year's deaths
  dat.appended_broad = yearsummary_broad(year_current)
```

## merge deaths and population files
```{r user-input3, include=TRUE}
# merge deaths and population files
dat.merged <- dat.appended_broad %>% left_join(pop.county.year, by=c('year','month','sex','age','fips'))

# reorder
dat.merged <- dat.merged[order(dat.merged$cause.group,dat.merged$cause.sub,dat.merged$cause.sub.sub,dat.merged$fips,dat.merged$sex,dat.merged$age,dat.merged$year,dat.merged$month),]
```

## add death rates based on adjusting for length of month and leap years
```{r user-input4, include=TRUE}
# leap year test
is.leapyear=function(year){
    return(((year %% 4 == 0) & (year %% 100 != 0)) | (year %% 400 == 0))
}
  
dat.merged$leap <- as.integer(is.leapyear(dat.merged$year))
  
# adjust deaths to a 31-day month
# Shouldn't make any difference as only looking at a month relative to same month in other years
# 30-day months = April, June, September, November (4,6,9,11)
# 31-day months = January, March, May, July, August, October, December (1,3,5,7,8,10,12)
# 28/29-day months = February (2)
dat.merged$deaths.adj <- ifelse(dat.merged$month %in% c(1,3,5,7,8,10,12), dat.merged$deaths,
                  ifelse(dat.merged$month %in% c(4,6,9,11), dat.merged$deaths*(31/30),
                  ifelse((dat.merged$month==2 & dat.merged$leap==0), dat.merged$deaths*(31/28),
                  ifelse((dat.merged$month==2 & dat.merged$leap==1), dat.merged$deaths*(31/29),
                  'ERROR'
                  ))))
dat.merged$deaths.adj <- as.numeric(dat.merged$deaths.adj)

# calculate rates and rate.adj
dat.merged$rate <- dat.merged$deaths / dat.merged$pop.adj
dat.merged$rate.adj <- dat.merged$deaths.adj / dat.merged$pop.adj
```

## investigate any na rows
```{r user-input5, include=TRUE}
# Look at rows which are matched and which ones are missing and why
#dat.merged.not.na = dat.merged[rowSums(is.na(dat.merged))==0,]
dat.merged.na = dat.merged[rowSums(is.na(dat.merged))>0,]
head(dat.merged.na,10)

# save na values
saveRDS(dat.merged.na,paste0(mortality.na.folder,'broad_cause_county_monthly_',year_current,'_na'))
```

## save each state and each year separately
```{r user-input6, include=TRUE}
# vector of unique states in dataset
states = sort(unique(dat.merged$state.fips))

# loop through all states in all years
for(state in states){
  dat.merged.subset = subset(dat.merged,state.fips==state)
  saveRDS(dat.merged.subset,paste0(mortality.year.folder,'broad_cause_county_monthly_',state,'_',year_current))
}

}
```