---
title: "Fix county codes for ethnicity groupings"
output: html_document
---

# First step to load packages and file locations etc.
```{r include=FALSE}
rm(list=ls())
 
# 1a Declare root directory, folder locations and load essential stuff
project.folder <- paste0(print(here::here()),'/')
source(paste0(project.folder,'0_00_create_folder_structure.R'))
source(paste0(functions.folder,'script_initiate.R'))
```

# Load formatted cdc bridged-race ethnicity data
```{r}
filename_in = paste0(population.formatted.folder,
                      'vintage_',vintage,'/Bridged-Race Population Estimates ethnicity ',start_year_cdc,' ',end_year_cdc,'.csv')
dat.1990.2020 = read_csv(filename_in)
```

# Load formatted cdc single-race data
```{r}
filename_in = paste0(population.formatted.folder,
                      'vintage_',vintage_single_race,'/Single-Race Population Estimates ethnicity ',start_year_cdc_single_race,' ',end_year_cdc_single_race,'.csv')
dat.2021.onwards = read_csv(filename_in)
```

# combine pre-1990 and cdc bridged-race (1990 onwards) data
```{r}
dat = bind_rows(dat.1990.2020, dat.2021.onwards) %>%
  arrange(year,fips,sex,ethnicity)
```

# Fix counties to be consistent all the way through
```{r}
dat = dat %>%
      mutate(fips = case_when(
        # Alaska FIPS codes to do here when have time
        fips== 'XXXXX' ~ 'XXXXX',
        fips== '08001' | fips== '08013' | fips== '08059' | fips== '08123' ~ '08014', # 08001, 08013, 08059, 08123 -> 08014
        fips== '12025' ~ '12086', #  12025 -> 12086
        fips== '30031' | fips== '30067'~ '30113', # 30113 -> 30031, 30067
        fips== '46113' ~ '46102', # 46113 -> 46102
        fips== '51560' ~ '51005', # 51560 -> 51005
        fips== '51780' ~ '51083', # 51780 -> 51083
        fips== '51515' ~ '51019', # 51515 -> 51019
        TRUE ~ fips
        )) %>%
      mutate(countyFips = str_sub(fips, start= -3)) # county fips 3-digit codes
```

# summarise by new merged consistent counties
```{r}
dat = dat %>%
  group_by(year, fips, stateFips, countyFips, sex, ethnicity) %>%
  summarise(pop=sum(pop))
```

# Save output
```{r}
for(year_selected in c(start_year_overall:end_year_cdc_single_race)){
  dat_year = dat %>% dplyr::filter(year==year_selected)
  if(year_selected<1990){
    filename_out = paste0(population.county.fixed.folder,
                      'pre_1990/pop_fixed_counties_ethnicity', year_selected,'.csv')  
  }
  if(year_selected>=1990&year_selected<=2020){
    filename_out = paste0(population.county.fixed.folder,
                      'vintage_',vintage,'/pop_fixed_counties_ethnicity_', year_selected,'.csv')
  }
  if(year_selected>=2021){
    filename_out = paste0(population.county.fixed.folder,
                      'vintage_',vintage_single_race,'/pop_fixed_counties_ethnicity_', year_selected,'.csv')
  }
  write_csv(dat_year,filename_out)
}
```