---
title: "Infer monthly population (5-year age groups)"
output: html_document
---

# First step to load packages and file locations etc.
```{r include=FALSE}
rm(list=ls())
 
# 1a Declare root directory, folder locations and load essential stuff
project.folder <- paste0(print(here::here()),'/')
source(paste0(project.folder,'0_00_create_folder_structure.R'))
source(paste0(functions.folder,'script_initiate.R'))
```

# Load population that has been fixed to have consistent counties
```{r}
dat_all= data.frame()
  for(year_selected in c(start_year_overall:end_year_cdc_single_race)){
    if(year_selected<1990){
      filename_in = paste0(population.county.fixed.folder,
                        'pre_1990/pop_fixed_counties_', year_selected,'.csv')  
    }
  if(year_selected>=1990&year_selected<=2020){
      filename_in = paste0(population.county.fixed.folder,
                        'vintage_',vintage,'/pop_fixed_counties_', year_selected,'.csv')
  }
  if(year_selected>=2021){
    filename_in = paste0(population.county.fixed.folder,
                      'vintage_',vintage_single_race,'/pop_fixed_counties_', year_selected,'.csv')
  }    
    dat_year=read_csv(filename_in)
    dat_all = data.table::rbindlist(list(dat_all,dat_year))
    rm(dat_year)
}
```

# Create 5-year age groupings
```{r}
dat_all = dat_all %>%
      mutate(age = as.numeric(case_when(
        age== '0' ~ '0',
        age== '5' ~ '5',
        age== '10' ~ '10',
        age== '15' ~ '15',
        age== '20' ~ '20',
        age== '25' ~ '25',
        age== '30' ~ '30',
        age== '35' ~ '35',
        age== '40' ~ '40',
        age== '45' ~ '45',
        age== '50' ~ '50',
        age== '55' ~ '55',
        age== '60' ~ '60',
        age== '65' ~ '65',
        age== '70' ~ '70',
        age== '75' ~ '75',
        age== '80' ~ '80',
        age== '85' ~ '85',
        TRUE ~ NA_character_))) %>%
  group_by(year, fips, sex, age) %>%
  summarise(pop=sum(pop))
```

# Assume each population value is for the end of June/beginning of July (month = 6)
```{r}
dat_all = dat_all %>% 
  mutate(month=6)
```

# Create complete grid of population
```{r}
years = sort(unique(dat_all$year))
fips = sort(unique(dat_all$fips))
sexes = sort(unique(dat_all$sex))
ages = sort(unique(dat_all$age))
months = c(1:12)

complete.grid = expand.grid(year=years,fips=fips,sex=sexes,age=ages,month=months) %>%
  arrange(year,fips,sex,age,month)
  
dat_complete = left_join(complete.grid, dat_all) %>%
  arrange(fips,sex,age,year,month)
```

# Infer monthly populations
```{r}
dat_complete = dat_complete %>%
  group_by(sex,age,fips) %>%
  mutate(pop = round(na.approx(pop, na.rm=FALSE))) %>%
  fill(pop, .direction = "downup") 
```

# Save output by year in GitHub project
```{r}
for(year_selected in c(min(dat_complete$year):end_year_cdc_single_race)){
  dat_year = dat_complete %>% dplyr::filter(year==year_selected)
  if(year_selected<1990){
    filename_out = paste0(population.5year.processed.folder,
                      'pre_1990/pop_monthly_5_year_age_groups_', year_selected,'.csv')  
  }
  if(year_selected>=1990&year_selected<=2020){
    filename_out = paste0(population.5year.processed.folder,
                      'vintage_',vintage,'/pop_monthly_5_year_age_groups_', year_selected,'.csv')
  }
  if(year_selected>=2021){
    filename_out = paste0(population.5year.processed.folder,
                      'vintage_',vintage_single_race,'/pop_monthly_5_year_age_groups_', year_selected,'.csv')
  }
  write_csv(dat_year,filename_out)
}
```

# Save output by year in local location
```{r}

new_population_data.5year = paste0(new_population_data,'5_year_age_groups/')

for(year_selected in c(min(dat_complete$year):end_year_cdc_single_race)){
  dat_year = dat_complete %>% dplyr::filter(year==year_selected)
  if(year_selected<1990){
    filename_out = paste0(new_population_data.5year,
                      'pre_1990/pop_monthly_5_year_age_groups_', year_selected,'.csv')  
  }
  if(year_selected>=1990&year_selected<=2020){
    filename_out = paste0(new_population_data.5year,
                      'vintage_',vintage,'/pop_monthly_5_year_age_groups_', year_selected,'.csv')
  }
  if(year_selected>=2021){
    filename_out = paste0(new_population_data.5year,
                      'vintage_',vintage_single_race,'/pop_monthly_5_year_age_groups_', year_selected,'.csv')
  }
  write_csv(dat_year,filename_out)
}
```